import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import TopSearchBar from "@/components/TopSearchBar";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-gray-50">
        <nav className="bg-[#1e3a8a] text-white p-4 shadow-md print:hidden">
          <div className="max-w-7xl mx-auto flex items-center justify-between gap-4">
            <div className="font-bold text-xl whitespace-nowrap hidden sm:block">Mini CRM</div>
            
            <TopSearchBar />

            <div className="flex gap-2 text-sm whitespace-nowrap overflow-x-auto">
              <a href="/dashboard" className="hover:bg-blue-800 px-3 py-2 rounded transition">📊 Dashboard</a>
              <a href="/quotation" className="hover:bg-blue-800 px-3 py-2 rounded transition">📝 ใบเสนอราคา</a>
              <a href="/customers" className="hover:bg-blue-800 px-3 py-2 rounded transition">👥 ฐานลูกค้า</a>
              <a href="/pricelist.html" target="_blank" className="hover:bg-blue-800 px-3 py-2 rounded transition">💰 PriceList</a>
            </div>
          </div>
        </nav>
        <main className="flex-1">
          {children}
        </main>
      </body>
    </html>
  );
}
